apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-secret
  labels:
    app: "mediawiki"
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  mediawiki-password: {{ default "" .Values.mediawiki.adminpassword | b64enc | quote }}