---
image:
  repository: sunnyktyagi/mediawiki
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  replicas: 2

# option to specify external database created by DaaS
externalDatabase:
  ## Database host
  host: localhost
  ## Database port
  port: 3306
  ## Database user
  user: mediawiki
  ## Database password
  password: 
  ## Database name
  database: mediawiki

# mediawiki admin password
mediawiki:
  adminpassword: 
  
# resources
limits:
    cpu: "250m"
    memory: "512Mi"
requests:
    cpu: "100m"
    memory: "256Mi"

## options for liveness and readiness probes
livenessProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
